'''
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence 
which do not exceed four million.

'''

def solve_problem(limit):
    # tip: every 3rd element of fibonacci sequence is even

    num1, num2 = 1, 1
    num3 = num1 + num2
    sum = 0

    while num2 < limit:
        sum += num3
        num1 = num3 + num2
        num2 = num1 + num3
        num3 = num1 + num2

    return sum 

if __name__ == '__main__':
    assert 4613732 == solve_problem(4000000)
